from setuptools import setup

setup(
    name='eventKafkaPostgres',
    version='0.1',
    packages=['', 'venv.lib.python3.7.site-packages.pip', 'venv.lib.python3.7.site-packages.pip._vendor',
              'venv.lib.python3.7.site-packages.pip._vendor.idna',
              'venv.lib.python3.7.site-packages.pip._vendor.pep517',
              'venv.lib.python3.7.site-packages.pip._vendor.pytoml',
              'venv.lib.python3.7.site-packages.pip._vendor.certifi',
              'venv.lib.python3.7.site-packages.pip._vendor.chardet',
              'venv.lib.python3.7.site-packages.pip._vendor.chardet.cli',
              'venv.lib.python3.7.site-packages.pip._vendor.distlib',
              'venv.lib.python3.7.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python3.7.site-packages.pip._vendor.msgpack',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.util',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.contrib',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.packages',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.lib.python3.7.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.7.site-packages.pip._vendor.colorama',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.7.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.7.site-packages.pip._vendor.lockfile',
              'venv.lib.python3.7.site-packages.pip._vendor.progress',
              'venv.lib.python3.7.site-packages.pip._vendor.requests',
              'venv.lib.python3.7.site-packages.pip._vendor.packaging',
              'venv.lib.python3.7.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python3.7.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.7.site-packages.pip._vendor.webencodings',
              'venv.lib.python3.7.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python3.7.site-packages.pip._internal', 'venv.lib.python3.7.site-packages.pip._internal.cli',
              'venv.lib.python3.7.site-packages.pip._internal.req',
              'venv.lib.python3.7.site-packages.pip._internal.vcs',
              'venv.lib.python3.7.site-packages.pip._internal.utils',
              'venv.lib.python3.7.site-packages.pip._internal.models',
              'venv.lib.python3.7.site-packages.pip._internal.commands',
              'venv.lib.python3.7.site-packages.pip._internal.operations', 'venv.lib.python3.7.site-packages.kafka',
              'venv.lib.python3.7.site-packages.kafka.admin', 'venv.lib.python3.7.site-packages.kafka.record',
              'venv.lib.python3.7.site-packages.kafka.vendor', 'venv.lib.python3.7.site-packages.kafka.metrics',
              'venv.lib.python3.7.site-packages.kafka.metrics.stats', 'venv.lib.python3.7.site-packages.kafka.consumer',
              'venv.lib.python3.7.site-packages.kafka.producer', 'venv.lib.python3.7.site-packages.kafka.protocol',
              'venv.lib.python3.7.site-packages.kafka.serializer', 'venv.lib.python3.7.site-packages.kafka.coordinator',
              'venv.lib.python3.7.site-packages.kafka.coordinator.assignors',
              'venv.lib.python3.7.site-packages.kafka.partitioner', 'venv.lib.python3.7.site-packages.psutil',
              'venv.lib.python3.7.site-packages.psutil.tests', 'venv.lib.python3.7.site-packages.psycopg2',
              'venv.lib.python3.7.site-packages.psycopg2.tests'],
    url='',
    license='',
    author='RAMESH GHIMIRE',
    author_email='rameshxghimire@gmail.com',
    description='A system that generates some events and passes the events through Aiven Kafka instance to '
                'Aiven PostgreSQL database.'
)
